### ISSUE TITLE
Launch/Close Program with Game

### ISSUE THREAD

**Issue by Dave247** [Haato3o/HunterPie#1]
Same as suggestion in Python version.
https://github.com/Haato3o/HunterPy/issues/1#issue-529729955

**Comment by Haato3o** [comment]
Added button to launch Monster Hunter with custom arguments, you can choose the executable location. (https://github.com/Haato3o/HunterPie/commit/e0788ffa218893dfaaa1d145dc03a03e7866572c)
Added option to close itself when HunterPie detects the game is no longer running. (https://github.com/Haato3o/HunterPie/commit/ec749249d850f676eb50a9584d303ec324080e29 )

I'll push the updates to the BETA branch first in case you want to test them.

**Comment by Dave247** [comment]
Thanks. Sorry i didn't get a chance to test it myself first but it all seems to be working as it should.

I did have one instance where the program loaded the map but then didn't find the player address but I haven't been able to reproduce it, so I'm going to leave it as a anomaly.

**Comment by Haato3o** [comment]
> I did have one instance where the program loaded the map but then didn't find the player address but I haven't been able to reproduce it, so I'm going to leave it as a anomaly.

I tried to reproduce that and might have found the issue, it should be fixed now. (https://github.com/Haato3o/HunterPie/commit/39c84a6c068baa25a8ac0f7a653d6391dba19337)
