### ISSUE TITLE
Background for Monster Widget

### ISSUE THREAD

**Issue by Glenugie** [Haato3o/HunterPie#100]
Would it be possible for the Monster Widget to have a dark, semi-transparent background (like the harvest box) to aid in visibility? It can be difficult to read details off the widget in bright areas (particularly coral highlands/hoarfrost reach).

**Comment by Haato3o** [comment]
You can change the styles for it by changing the `HunterPie.Resources/UI/Overwrite.xaml` file.

## Widget Background

Paste the following code inside the `ResourceDictionary` tags in your `Overwrite.xaml`. It will make the widget background darker.
```xml
<Style x:Key="OVERLAY_MONSTER_BACKGROUND" BasedOn="{StaticResource OVERLAY_MONSTER_BACKGROUND}" TargetType="StackPanel">
    <Setter Property="Background" Value="#50000000"/>
</Style>
```
![image](https://user-images.githubusercontent.com/35552782/95101686-d20afb80-0708-11eb-9570-7007484e2083.png)
