### ISSUE TITLE
One suggestion for monster widget

### ISSUE THREAD

**Issue by wzh9969** [Haato3o/HunterPie#105]
Hi, I have used HelloWorld for over one year but recently I found this overlay far more clear and easier to configure. But I cannot get rid of my old overlay because it can show the **action** of all monsters (such as 'Damage Sleep', 'Tired' or the name of current move). I'm not sure whether this is implemented in this overlay or not since I cannot find it in the settings. Currently I am using both overlays but I hope monster actions can be shown by this overlay.

Other parts seem perfect and thanks for the great work.

**Comment by Haato3o** [comment]
Sorry but things are not as simple as that, although I already know where the monster action id is, mapping each action for all the +60 monsters is not something I'm willing to do, considering each monster has ~120 different actions, that would be at least 7k different actions I'd have to map by hand and I don't have the time nor energy for that and I don't think there's any open-source data dump with the monsters actions by id open publicly, I could be wrong though so let me know otherwise.

**Comment by wzh9969** [comment]
I'm sorry to hear that. I don't know how exactly HelloWorld implements this but action names seem to be built in the game since I cannot translate the name of actions in the configure file. I searched the forum and found the author said "I don't know how many of them there are, or where to find them." It's hard to study how HelloWord works because there is no access to its code, but maybe I will try when I have time.

**Comment by wzh9969** [comment]
Well, I think I find something. 
I use Cheat Engine to search for the plain text of action names in the memory. I find some unique actions like `nActEm001::HighPowerBreath` (@0x14316E878, picture below) and some template actions like `nActEmCommon::IdleToAngleBlendSequenceFlyS<nActEm013::cEm013SubAction>` (@0x142F81FB0). The address is fixed and a search for `"nActEm" + id + "::"` can get many names in a sequential space. I don't know where or what the action id is but maybe the id is just index or some kind of offset.
![0x14316E878](https://user-images.githubusercontent.com/37007622/95680790-9d1e0d80-0c0e-11eb-9c30-518639a35ff5.jpg)

**Comment by Haato3o** [comment]
Oh, that makes sense! So the game keeps string references to class functions, in that example it's for Rathian (em001), I'll give it a look and try to find what points to the right string or if the action id is actually an index for that string array. Good job, by the way.

**Comment by wzh9969** [comment]
Thanks and glad to help!

**Comment by wzh9969** [comment]
That's a great news! Looking forward to the new version. 👍
