### ISSUE TITLE
Monster target with a captured monster

### ISSUE THREAD

**Issue by faanlez** [Haato3o/HunterPie#108]
Choosing a target for monster widget when there is a dead monster can show wrong monster's info. It gets fixed when the corpse despawns. Might be because the dead monster was originally first in the list and now the new target is also first?

**Comment by Haato3o** [comment]
Dead monster or captured monster? That's a known issue for captured monsters (since I haven't found what exactly indicates whether a monster is captured or not), will hopefully fix it after implementing monster action tracker.

**Comment by faanlez** [comment]
Might have been captured every time it happened, yeah.

**Comment by Haato3o** [comment]
(https://github.com/Haato3o/HunterPie/commit/a2971f2b4941a325ff15ecd430d0f71e65725279) Fixed capture issue, the update is live on BETA if you want to test it
