### ISSUE TITLE
Decorations export is missing decorations

### ISSUE THREAD

**Issue by UncleClapton** [Haato3o/HunterPie#109]
First off, Thanks for implementing the data exporter 😄 

Since the latest patch it seems the exporter is missing 3 decorations. It outputs 401 values while honey hunter expects 404, and this ends up breaking Honey's jewel import. Perhaps it's missing the 3 newly added jewels?

**Comment by Haato3o** [comment]
Oh, it's not missing the new decorations, I just forgot to update the maximum jewels value in the [decorations exporter](https://github.com/Haato3o/HunterPie/blob/master/HunterPie/Core/Integrations/Honey/Honey.cs#L346). Gonna fix that, thanks for reporting!

**Comment by Haato3o** [comment]
Fixed in https://github.com/Haato3o/HunterPie/commit/718860025534eec17ca1fd382174ed946ecf957e. It's live in the HunterPie BETA, but I haven't pushed it to master yet, will push it with v1.0.3.98.
