### ISSUE TITLE
Gadget Overlay Timers

### ISSUE THREAD

**Issue by Dave247** [Haato3o/HunterPie#11]
I noticed that a recent update has added certain gadgets like the Health and Cleanser booster has been added to the overlay, where it displays the time remaining until the booster expires. I quite like that though I have some ideas for a few imporvets that could be made to it.

The main one is that the coloured circle could change to give a visual representation as to how much time is left, starting from a full circle and then depleting until it's almost empty.
The fanciest way to do this would be to have it as a slow but constant transition but I imagine that would be quite tricky to implement and require some fancy math.
An alternative would be to have four different image states, one for when completely full, 3/4 empty, half and finally 1/4 empty. While that would still require some work to implement I image it to be a lot less complicated and would act as a nice bridge to setting things up if you were to keep building on that to make it fancier.

Lastly of course having a seperate toggle and x/y position for it would probably be a good idea in case for whatever reason someone may wish to turn it off as they don't want it or they do but it's getting in their way.
This is probably more interesting how there is an option in the game settings to individually turn on and off different parts of the UI which I don't remember there being before the Iceborn patch.

**Comment by Haato3o** [comment]
I don't really understand what you're asking LOL. Are you talking about the mantle/boosters timer and cooldown? Because that one already have a donut-shaped progress bar that shows how much time is left

**Comment by Dave247** [comment]
Ah you're right sorry! I could've sworn that only a few days ago it was only a constant image and not updating. Nevermind then.
