### ISSUE TITLE
Selected ailments not saving

### ISSUE THREAD

**Issue by MintyFreshGum** [Haato3o/HunterPie#116]
When trying to display only a subset of all the ailments, the overlay instead displays them all. Re-saving will display the proper list, but upon a new quest start, the entire ailment list is again displayed

**Comment by MintyFreshGum** [comment]
I would label this as a bug, but I'm not sure how

**Comment by Haato3o** [comment]
Hey, thanks for reporting! I fixed it and pushed a hotfix now (https://github.com/Haato3o/HunterPie/commit/ff34f6243c8b75e85308627666a7b02869dc1f77).

**Comment by Haato3o** [comment]
Closing this as it has been fixed.
