### ISSUE TITLE
Rich Presence Gathering Hub Names

### ISSUE THREAD

**Issue by Dave247** [Haato3o/HunterPie#12]
Just a really small one, I noticed that the `largeImageText` tooltip shows "Gathering Hub" for both the Asteria and Selina areas, despite how there's different images. I think that the tooltip  should probably be updated to include the name of which area's Gathering Hub you are in just to be able to better differentiate between them.

**Comment by Haato3o** [comment]
Astera gathering hub will now show as `Astera Gathering Hub` and seliana's will show as `Seliana Gathering Hub`
