### ISSUE TITLE
Timer stops at 10 000 seconds in Guiding Lands

### ISSUE THREAD

**Issue by PotionClair** [Haato3o/HunterPie#126]
I thought it was a random bug, but the timer stopped exactly at 2 hours 48 minutes 40 seconds, which is ((2*60)+48)*60 = 10000 seconds.

Example [here](https://www.youtube.com/watch?v=uIlgmGqbvow&t=17930s) at 4:58:56. Happens maybe in Expeditions too?

**Comment by Haato3o** [comment]
That's a known issue, unfortunately I haven't found any in-game timer that would go past 10000 seconds (I've found +30 different timers and they all are capped at 10k seconds), only way to fix it would be to calculate the elapsed time by myself, but that wouldn't  be as accurate for quests as the current timer.
