### ISSUE TITLE
Starting Game Areas Missing Info

### ISSUE THREAD

**Issue by Dave247** [Haato3o/HunterPie#13]
I started a new game in order to get access to the original Chamber of Five location and ended up finding a few extra areas.

ZoneID 401 is at the very start when you get control of your character following the first few cutscenes, where you get knocked off the ship and all onto Zora's back. I've included what is hopefully a good screenshot in #9 

Next you end up in ZoneID 406 which is a special version of the Ancient Forest map made to be extremely limited in its area and pathing that is only used for this section of the game. You should still be able to use the same image and label it as the Ancient Forest though as there didn't seem to be any visual changes from the regular Ancient Forest.

Following that you end up in Asteria and despite some of the restrictions is the same map as the regular Asteria (301) before going on your first quest which is again the proper version of the ancient forest (101).

One other thing to note is that after when you first create a character, the console will spit out `Logged on PLAYER 1` every single tic until you get to the character creation screen, and then again a few more times until it finds ZoneID 401 which is when it finally stops, and then just change to keeping track of whenever the equipment address changes (which seems to be quite often).
While this likely is a very minor thing as you would only ever go through this stage once in the game and might not even have HunterPie open for it, I wanted to still mention it in case it may still be relevant.

**Comment by Haato3o** [comment]
Thanks, I'll add the images and look into the PLAYER 1 thing and fix it.
