### ISSUE TITLE
can you upload latest version of the package?  thanks

### ISSUE THREAD

**Issue by GodLiyf** [Haato3o/HunterPie#137]
I am from China and cannot use the built-in update function due to network problems. I hope you can upload latest version of the zip package. please!!! thank you very much!

**Comment by MK99MA** [comment]
The latest master branch version (1.0.4) is uploaded [here](https://github.com/Haato3o/HunterPie/releases/tag/v1.0.4) Are you referring to (small) bug fix updates?

Also, which version are you at? At least I think Haato tried to tackle this problem before by moving the files to another server ([as stated here](https://forums.nexusmods.com/index.php?showtopic=8445968/#entry79500423))

**Comment by Haato3o** [comment]
Latest one should be [here](https://github.com/Haato3o/HunterPie/releases/tag/v1.0.5) now
