### ISSUE TITLE
Rich Presence Quest Names

### ISSUE THREAD

**Issue by Dave247** [Haato3o/HunterPie#14]
Was it ever a consideration to add the quest names to Rich Presence? I can understand why if you decided not to implement that as I can only imagine it to be a massive undertaking due to the sheer amount of quests there are in the game, and how it would be hard to get the correct references when you can't even access some quests depending on so many different things.

**Comment by Haato3o** [comment]
It was actually, but then I would need to find the address that shows the quest ID and then map all quest names, but that's too much work.

**Comment by Dave247** [comment]
Yeah I figured, that's ok I just wanted to mention it.
