### ISSUE TITLE
something wrong with my computer?

### ISSUE THREAD

**Issue by nnkn** [Haato3o/HunterPie#141]
when I lauch the app , I can see nothing but these(see pic attached )
<img width="540" alt="1" src="https://user-images.githubusercontent.com/22342244/107201430-edc63b80-6a33-11eb-8c51-b21421be2ed5.png">
<img width="739" alt="2" src="https://user-images.githubusercontent.com/22342244/107201443-f28aef80-6a33-11eb-972b-08c03be8e30d.png">

I changed the graphic card driver for several version, but nothing changed.

what can I  do?

**Comment by Haato3o** [comment]
I honestly have no idea, but it's definitely some local problem
