### ISSUE TITLE
Monster Mantle Overlay Info Broken

### ISSUE THREAD

**Issue by Dave247** [Haato3o/HunterPie#15]
I've noticed that the mantle cooldown timer doesn't seem to be appearing in the current version of the program. I have the general overlay enabled and even tired with the monster health overlay, but the mantle cooldown still wasn't showing up.

**Comment by Haato3o** [comment]
I've had a few people test the mantle cooldown widget for me and they all said it was working. Check if they're not appearing off screen or if the mantles are even enabled, you can change that in settings. Also, if none of those works, send me a screenshot of your console so I can see if it's even detecting the equipment address.

**Comment by Dave247** [comment]
I'll look at it again but more closely and keep an eye on the console this time. For reference I last tested this in the Special Arena but I wouldn't think that the map would affect from it showing or not.

**Comment by Dave247** [comment]
Ah nevermind I just realised I'm a bit of a idot sorry. I was thinking "mantle" as mounting the monster for some reason, like how games often use the word for when you climb something. My bad! ^^;
