### ISSUE TITLE
Add Origin Isle location

### ISSUE THREAD

**Issue by TheFuzzy** [Haato3o/HunterPie#16]
Name: Origin Isle
Code: st412, st413

![20200204082423_1](https://user-images.githubusercontent.com/4396695/74079589-6a66b880-4a74-11ea-8e14-1dd56f9f2fcc.jpg)

Context: st412 is the first part of Origin Isle, and won't be accessible after the story ends. If you want to have a unique image for it anyway, you can use this one:

![20200208124120_1](https://user-images.githubusercontent.com/4396695/74079595-88341d80-4a74-11ea-9f89-35088b23e981.jpg)

**Comment by Haato3o** [comment]
Thanks! I'll add it and Seliana Supply Cache (#17) and will push a patch today.

**Comment by Haato3o** [comment]
Done!
