### ISSUE TITLE
Abnormality Overlay Bugging Out

### ISSUE THREAD

**Issue by LeMustardHomie** [Haato3o/HunterPie#161]
I have no clue what happened but earlier today whenever I press the w key while in game these large gray boxed pop up on my screen. I've already tried restarting and disabling it, but I couldn't find where it showed the key bind nor could I find a "reset to default settings" button. A little help would be lovely.

**Comment by Haato3o** [comment]
You probably set the `Toggle Design Mode` hotkey to <kbd>W</kbd> by accident, just go to your Overlay settings and change it to something else.
![image](https://user-images.githubusercontent.com/35552782/117588759-efb79d80-b0fb-11eb-94fc-81afe04b6f2a.png)

**Comment by LeMustardHomie** [comment]
Where can i find that

**Comment by Haato3o** [comment]
In the Overlay settings.
![image](https://user-images.githubusercontent.com/35552782/117589186-7ec5b500-b0fe-11eb-959d-4703e348e781.png)

**Comment by LeMustardHomie** [comment]
Thank you so much!
