### ISSUE TITLE
Getting HunterPie (v1.0.5) to run on Linux with Steam Proton

### ISSUE THREAD

**Issue by 0fbcb238c0** [Haato3o/HunterPie#171]
Hello,

using the following modified script, taken from https://bakkesmod.fandom.com/wiki/Running_in_Linux_/_Steam_Proton, I've managed to start HunterPie as well as SmartHunter.

The following launch option has to be set `./mhwd_sh.sh && echo %command%`
```
#!/bin/sh
#Start HunterPie
protontricks -c 'STEAM_COMPAT_DATA_PATH="/mnt/Spiele/SteamLibrary/steamapps/compatdata/582010/" "/mnt/Games/SteamLibrary/steamapps/common/Proton - Experimental/proton" run  "/mnt/Games/SteamLibrary/steamapps/compatdata/582010/pfx/drive_c/users/steamuser/My Documents/HunterPie/HunterPie.exe"' 582010 2> hunterpie-wine.log &
#Start MHWD
mangohud MANGOHUD_CONFIG=position=top-right gamemoderun STEAM_COMPAT_DATA_PATH="/mnt/Games/SteamLibrary/steamapps/compatdata/582010/"  "/mnt/Games/SteamLibrary/steamapps/common/Proton - Experimental/proton" run "/mnt/Games/SteamLibrary/steamapps/common/Monster Hunter World/MonsterHunterWorld.exe" &
#wait until MonsterHunterWorld.exe is running
while ! killall -0 MonsterHunterWorld.exe 2> /dev/null; do
    sleep 1
done
#wait for closing MHWD
while killall -0 MonsterHunterWorld.exe 2> /dev/null; do
    sleep 1
done
killall HunterPie.exe
```
The problem with this is that while HunterPie is showing that it is hooked, it is not displaying any info inside the of game (v15.11.01). 
The same applies to SmartHunter the latter outputting that certain addresses cannot be found, which is probably the reason for both of those programs not working correctly under linux.
Maybe someone capable of it can check where those addresses are compared to windows?
I myself sadly have no experience in such things and don't quite know where to start.

Thanks for your help!

**Comment by HonzoNebro** [comment]
I've made some changes trying to make it work with MHRise, appID is 1446780.
Launch options 
./~/.steam/debian-instalation/steamapps/common/MonsterHunterRise/mhpie.sh && echo %command%

This doens't work at all, maybe someone can make it work?

> #!/bin/sh
> #Start HunterPie
> protontricks -c 'STEAM_COMPAT_DATA_PATH="~/.steam/debian-instalation/steamapps/compatdata/1446780/" "~/.steam/debian-instalation/steamapps/common/Proton - Experimental/proton" run  "~/.steam/debian-instalation/steamapps/compatdata/1446780/pfx/drive_c/users/steamuser/My Documents/HunterPie/HunterPie.exe"' 1446780 2> hunterpie-wine.log &
> #Start MHWD
> STEAM_COMPAT_DATA_PATH="/mnt/Games/SteamLibrary/steamapps/compatdata/1446780/"  "/mnt/Games/SteamLibrary/steamapps/common/Proton - Experimental/proton" run "/mnt/Games/SteamLibrary/steamapps/common/MonsterHunterRise/MonsterHunterRise.exe" &
> #wait until MonsterHunterWorld.exe is running
> while ! killall -0 MonsterHunterRise.exe 2> /dev/null; do
>     sleep 1
> done
> #wait for closing MHWD
> while killall -0 MonsterHunterRise.exe 2> /dev/null; do
>     sleep 1
> done
> killall HunterPie.exe

**Comment by Haato3o** [comment]
> I've made some changes trying to make it work with MHRise, appID is 1446780. Launch options ./~/.steam/debian-instalation/steamapps/common/MonsterHunterRise/mhpie.sh && echo %command%
> 
> This doens't work at all, maybe someone can make it work?
> 
> ```
> #!/bin/sh
> #Start HunterPie
> protontricks -c 'STEAM_COMPAT_DATA_PATH="~/.steam/debian-instalation/steamapps/compatdata/1446780/" "~/.steam/debian-instalation/steamapps/common/Proton - Experimental/proton" run  "~/.steam/debian-instalation/steamapps/compatdata/1446780/pfx/drive_c/users/steamuser/My Documents/HunterPie/HunterPie.exe"' 1446780 2> hunterpie-wine.log &
> #Start MHWD
> STEAM_COMPAT_DATA_PATH="/mnt/Games/SteamLibrary/steamapps/compatdata/1446780/"  "/mnt/Games/SteamLibrary/steamapps/common/Proton - Experimental/proton" run "/mnt/Games/SteamLibrary/steamapps/common/MonsterHunterRise/MonsterHunterRise.exe" &
> #wait until MonsterHunterWorld.exe is running
> while ! killall -0 MonsterHunterRise.exe 2> /dev/null; do
>     sleep 1
> done
> #wait for closing MHWD
> while killall -0 MonsterHunterRise.exe 2> /dev/null; do
>     sleep 1
> done
> killall HunterPie.exe
> ```

Not really sure what you're trying to do, this version of HunterPie doesn't even support MHR. For support for both games you should look into [HunterPie v2](https://github.com/Haato3o/HunterPie-v2).

**Comment by Haato3o** [comment]
Also, HunterPie uses Windows memory reading APIs, which is probably why it doesn't work on Steam Proton, though I don't have any experience using Steam Proton so I don't know how it works, but the game addresses are probably not the same as running natively. I don't plan on adding support for Linux, that would be way too much work to maintain.
