### ISSUE TITLE
Harvest box slots

### ISSUE THREAD

**Issue by namidairo** [Haato3o/HunterPie#18]
Looks like you loop for 31 slots [here](https://github.com/Haato3o/HunterPie/blob/e95948134cf8ac96cbc094e23aea36ff7ef8666c/HunterPie/Core/Player/Player.cs#L401), when the capacity can be up to 50, depending on optional quest completion.

**Comment by Haato3o** [comment]
Oh, Thanks! I'll change it to scan all 50 slots.

**Comment by Haato3o** [comment]
Done!
