### ISSUE TITLE
Format exception crash

### ISSUE THREAD

**Issue by EliphasNUIT** [Haato3o/HunterPie#19]
In MonsterData.cs, GetMonsterCrownByMultiplier float.Parse throws a format exception due to culture differences.

A quick fix would be adding CultureInfo.InvariantCulture to the method but I have not gone through the whole code to see if other similar issues could arise elsewhere, which would most likely require setting the current culture on the Application/Thread.CurrentThread to be safe.

**Comment by Haato3o** [comment]
Did it crash when Rajang was in the map? I fixed this float parse problem a while ago but just noticed I forgot to change Rajang's size data https://github.com/Haato3o/HunterPie/blob/master/HunterPie/Core/Monster/MonsterData.xml#L85

**Comment by EliphasNUIT** [comment]
Yep, I have encountered this problem only with Rajang on the map.

**Comment by Haato3o** [comment]
Yeah, I just pushed the fix to both branches (BETA and master), it shouldn't be an issue anymore. Lemme know if you find any other bugs!
