### ISSUE TITLE
can you increase a new function？

### ISSUE THREAD

**Issue by Ilostmyflp** [Haato3o/HunterPie#198]
hunting over time huter name and damage and outputpercentage Language Bar txt format input let everyone play can see the outputdata。

**Comment by Ilostmyflp** [comment]
sorry my english bad i come from china ，this is chinese problem：您可以添加一个新的功能吗？在游戏结束时，可以让游戏内的输出数据“游戏玩家ID，输出伤害，输出百分比”以数据的格式，在语言栏中输出，以便能够让所有其他玩家看到数据，《别忘记添加中文》

**Comment by haato3o** [comment]
No, I'm not going to add the ability to paste damage numbers into the party chat

**Comment by Ilostmyflp** [comment]
![QQ图片20231224093739](https://github.com/HunterPie/HunterPie-legacy/assets/154713235/0870fbb0-75b4-4b05-9212-9eec7aa4f55e)
fine may be just my vanity haunt，mhw not have Blood volume strip，i hlep other player time，cant obtain fulfillment like soul games
