### ISSUE TITLE
UI doesn't show up unless I'm tabbed off

### ISSUE THREAD

**Issue by Shawner1234** [Haato3o/HunterPie#199]
Hi so I recently download Hunter Pi and I can't see any of the UI until I click off the game to go try to fix it and then it appears but when I click back onto the game it disappears again.

**Comment by haato3o** [comment]
From the FAQ.
![image](https://github.com/HunterPie/HunterPie-legacy/assets/35552782/07b8e387-c815-4c5b-b623-89e90c705c8f)
