### ISSUE TITLE
Changes to Monster Overlay

### ISSUE THREAD

**Issue by Dave247** [Haato3o/HunterPie#2]
I have a few ideas as to how the monster overlay could be changed/improved, as while having a heath bar for the monsters does provide a useful tool, having it show for all of the monsters in the map as soon as you load in can seem a bit too hacky, and ruin some of the fun of the game.

One solution would be to only show the monsters who have been discovered/sighted, but I don't know how difficult or possible that would be to even track.

Another, potentially better solution would be to only show the bar when locked onto a monster as that would mechanically make the most sense, though again I don't know if it would be possible to track from outside the game.
This method would also add the extra steps to move the position to differ from the current setup, while opening up the avenue to add more options to customize it such as size as there would only be one bar on the screen at any given time.

**Comment by Haato3o** [comment]
I don't know if there's a way to track wether the monster was discovered or not and so far I haven't found the memory addresses that handle which monster you're locking onto (I know there is one, just need to find where it is).
I will add more customization options to the monsters HP overlay in the future though, just need to finish implementing rich presence. Thanks for the suggestions though :)

**Comment by FallenKN** [comment]
I belive I have seen other tools handle it by checking if monsters hp change or not and when they do not for a certain time just stop displaying them

**Comment by Haato3o** [comment]
Yea, that would work too. I might do that after finishing all the other stuff in my priority list

**Comment by Haato3o** [comment]
Done!
