### ISSUE TITLE
No source code license in the repository

### ISSUE THREAD

**Issue by kjwilcox** [Haato3o/HunterPie#25]
By linking the GitHub from the HunterPie application, it's sort of implied that the project is open-source. However the repository doesn't have a `LICENSE.txt` file (or similar) indicating an open-source license.

> Without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.

It would be nice to add one so that folks who stumble on this repo know the source code status and whether they can legally make derivative works.

I recommend the MIT license (SmartHunter uses that), but here's some [information on open-source licenses](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository) in case you aren't familiar with the options.

Happy to make a PR and do this if you agree with my assessment.

**Comment by Haato3o** [comment]
Done :)
