### ISSUE TITLE
separate positioning for each monster or align left, right and middle

### ISSUE THREAD

**Issue by Pinezerka** [Haato3o/HunterPie#29]
enhancement 

![Annotation 2020-03-27 011530](https://user-images.githubusercontent.com/39213507/77660681-8cd37780-6fc9-11ea-95a3-4ffc81019ae9.jpg)

**Comment by Haato3o** [comment]
That would require me to rewrite some of the code for the monster widget, add separate configs and it's not something I wanna do anytime soon

**Comment by Pinezerka** [comment]
even to just make it load from the right rather then the middle? haha ill try not let my OCD get to me
