### ISSUE TITLE
Track when on Main Menu

### ISSUE THREAD

**Issue by Dave247** [Haato3o/HunterPie#3]
A relatively minor thing, bur Is it possible for the program to track when the player is in the main menu and send that info to Discord? Short of it not being able to be tracked I don't see why it shouldn't be added as despite how a typically player would not spend that long in the menu, it still exists as a valid game state.

**Comment by Haato3o** [comment]
Yea, that is possible, I'll start working on it soon.

**Comment by Haato3o** [comment]
I'm starting to implement it, will probably finish it after I'm done with the core code refactoring.

![image](https://user-images.githubusercontent.com/35552782/70016052-04ceeb00-155e-11ea-8484-df3296237268.png)

**Comment by Dave247** [comment]
Looks good!

**Comment by Haato3o** [comment]
Done
