### ISSUE TITLE
Add secondary part break bar

### ISSUE THREAD

**Issue by nicodiaz55** [Haato3o/HunterPie#30]
We currently have a counter that tells us how many times we have "broken" a part (causing the monster to flinch). But the part itself is not completely broken until a certain amount is reached. So we could add a secondary bar to show how close that part is about to break.

This could be useful for example for Safi'jiiva's siege, so players could focus on the parts about to break / ignore already broken parts.

Visually:

- change the part break bar to look like the HP bar with the stamina bar, so we have a bar for part's health and a second one for the part's breaking point.
- or change the counter to something like "X/Y", where X is the amount of time we emptied the part's health, and Y the total to break the part (X of course can be greater than Y at some point).
- or change the color of the counter to indicate that this part is already broken.
- or all these options at the same time (lol).

Now, I understand that this break value cannot be read from memory, so we have to manually collect these numbers and hardcode them.

I can help you compile a list of these values for all the monsters, if this seems to be a good idea to add.

**Comment by nicodiaz55** [comment]
Sorry, maybe I didn't express myself correctly (English is not my primary language). I'll try again:

Yes, we currently have bars that identify each breakable part. These bars indicate how much remaining health they have, and a number that indicates how many times we emptied that health bar.

But to *really* break monster parts, we must empty their health bar a certain number of times. For example, Namielle's head breaks after we have emptied her head's health bar about 4 or 5 times if I recall correctly.

So, what I wanted to add, if possible, is an additional bar per part (or modify the number on the left) that indicates how many times we must empty his health bar to break that part.

Something like this:
![image](https://user-images.githubusercontent.com/7559414/78299406-3b1c7700-750c-11ea-96b5-1f26ca884526.png)

Or well, the design could be better, but that's what I'm trying to say: know how many times we need to empty the part's health bar to break that part.

**Comment by Haato3o** [comment]
Ooh, I see now what you meant. Hmm, I think making it like your second example (the one that shows 1/5 inside the counter prism) would be easiest way to do it, since it wouldn't require me to re-design the monster part control again (and rewrite some of the code for it).
Although, yeah, we would have to hardcode all the values (assuming they are all static and not altered by any multiplier/factor in game).

**Comment by nicodiaz55** [comment]
Excellent! Yes, I think modifying only the number in the counter prism would be enough.

From what I remember in all my hunts, they always take the same number of times to break them.

Some parts show no visual indication that they are broken (like "Body" I think), they can be left as they are now.

The most difficult parts would be Safi'jiiva's head and the horns of some monsters: they can be broken twice ... maybe choose the highest number ("completely broken")?

I will collect all those values ​​and test while I can, since we are in quarantine and I can't go anywhere lol.

Thanks for taking this suggestion in count! And thank you for making  this software too, it has really cool features.

**Comment by kyoma** [comment]
For the head (or other double breaks) I would say maybe do "1/5" and then after first break it becomes "5/10".

**Comment by nicodiaz55** [comment]
Hello!

I finished testing all monsters from base game (except Kulve, Behemoth, Leshen and Ancient Leshen, I need a team for that).

Some things to pay attention:

- Some parts break two times (see Radobaan, Ugaraan, Odogaron, Diablos, Black Diablos and Nergigante)
- Some parts depends on monster's total health to break (see Teostra, Lunastra and Kushala Daora)
- Some parts are not working (bug?) (see Pukei-Pukei, Odogaron, TziTzi-Ya-Ku, and Vaal Hazak)


This is what I found:
```
Great Jagras:
	Breakable:
		Head -> 2
		Arms -> 1
		Abdomen -> 3
	Unbreakable:	
		Body
		Legs
		Tail

Kulu-Ya-Ku:
	Breakable:
		Head -> 1
		Arms -> 1
	Unbreakable:
		Legs
		Tail
		Rock -> Is not a monster's part (but breaks each time at 1)

Pukei-Pukei:
	Breakable:
		Removable Tail -> 1
		Head -> 2
		Left Wing -> 1
		Right Wing -> 1
		Body -> 1
	Unbreakable:
		Left Leg
		Right Leg
		Tail
	Unknown:
		Breakable Head -> sometimes stuck in 1 after decreasing health, but nothing really happens. Other times, health doesn't even decreases.

Barroth:
	Breakable:
		Breakable Head -> 1
		Muddy Head -> 1
		Muddy Body -> 1
		Arms -> 1
		Muddy Arms -> 1
		Left Leg -> 1
		Muddy Left Leg -> 1
		Right Leg -> 1
		Muddy Right Leg -> 1
		Muddy Tail -> 1
		Removable Tail -> 1
	Unbreakable:
		Tail
		Head
		Body
		
Jyuratodus:
	Breakable:
		Head -> 4
		Muddy Head -> 1
		Body -> 1
		Muddy Body -> 3
		Muddy Tail -> 1 
		Tail -> 3
	Unbreakable:
		Muddy Left Leg
		Muddy Right Leg
		Left Leg
		Right Leg
		
Tobi-Kadachi:
	Breakable:
		Head -> 2
		Mane -> 1
		Abdomen -> 1 (actually front legs)
		Tail -> 4
	Unbreakable:
		Legs
		Body
		
Anjanath:
	Breakable:
		Removable Tail -> 1
		Head -> 5
		Left Leg -> 3
		Right Leg -> 3
	Unbreakable:
		Tail
		Body
		
Rathian:
	Breakable:
		Removable Tail -> 1
		Head -> 2
		Body -> 1
		Left Wing ->  1
		Right Wing ->  1
	Unbreakable:
		Left Leg 
		Right Leg
		Tail

TziTzi-Ya-Ku:
	Breakable:
		Head Left -> 2
	Unbreakable:
		Head Right -> does nothing when health decreases, only Head Left breaks the head.
		Arms
		Legs
		Tail
		
Paolumu:
	Breakable:
		Removable Balloon -> 1
		Left Wing -> 1
		Right Wing -> 1
		Body -> 1
		Tail -> 1
	Unbreakable:
		Head
		Balloon
		Left Leg
		Right Leg

Great Girros:
	Breakable:
		Head -> 2
		Removable Tail -> 1
		Arms -> 1
	Unbreakable:
		Body
		Legs
		Tail
		
Radobaan:
	Breakable:
		Removable Tail -> 1
		Jaw -> 1, 2
		Back -> 1, 2
		Left Bone -> 1, 2
		Right Bone -> 1, 2
	Unbreakable:
		Head
		Body
		Left Leg
		Right Leg
		Tail

Legiana:
	Breakable:
		Head -> 2
		Body -> 1
		Left Wing -> 1
		Right Wing -> 1
		Tail -> 1
	Unbreakable:
		Left Leg
		Right Leg

Odogaron:
	Breakable:
		Tail -> 1
		Removable Tail -> 1, but something's wrong... it regains health and tail is cut at random numbers. Maybe wrong memory address?
		Head -> 1, 2
		Arms -> 1
		Legs -> 1
	Unbreakable:
		Body
		
Rathalos:
	Breakable:
		Body -> 1
		Head -> 2
		Left Wing -> 1
		Right Wing -> 1
		Removable Tail -> 1
	Unbreakable:
		Tail
		Left Leg
		Right Leg
		
Diablos:
	Breakable:
		Removable Horns -> 1, 2
		Removable Tail -> 1
		Body -> 1
	Unbreakable:
		Tail
		Head
		Left Wing
		Right Wing
		Left Leg
		Right Leg
		
Kirin:
	Breakable:
		Head -> 8 (Horn)
	Unbreakable:
		Arms (Front legs)
		Legs
		
Zorah Magdaros:
	Breakable:
		Head -> 1 (Beard)
		Chest -> 1
		Central Exhaust Organ -> 1 (but no health is decreased)
		Head Exhaust Organ -> 1 (but no health is decreased)
		Crater Exhaust Organ -> 1 (but no health is decreased)
		Rear Exhaust Organ -> 1 (but no health is decreased)
		Left Weak Shell -> 1
		Right Weak Shell -> 1
	Unbreakable:
		Body
		Left Arm
		Right Arm
		Tail
		Shell
		
Dodogama:
	Breakable:
		Removable Tail -> 1
		Head -> 5
		Arms -> 1
	Unbreakable:
		Body
		Legs
		Tail

Pink Rathian:
	Breakable:
		Removable Tail -> 1
		Head -> 2
		Body -> 1
		Left Wing -> 1
		Right Wing -> 1
	Unbreakable:
		Left Leg
		Right Leg
		Tail
		
Bazelgeuse:
	Breakable:
		Removable Tail -> 1
		Head -> 2
		Left Wing -> 1
		Right Wing -> 1
		Body -> 1
	Unbreakable:
		Tail
		Legs
		
Deviljho:
	Breakable:
		Head -> 3
		Chest -> 5
		Removable Tail -> 1
	Unbreakable:
		Tail
		Arms
		Rear
		Left Leg
		Right Leg
		Body

Lavasioth:
	Breakable:
		Head -> 6
		Body -> 2
		Tail -> 4
		Left Leg -> 4
		Right Leg -> 4
	Unbreakable:
		Abdomen

Uragaan:
	Breakable:
		Removable Tail -> 1
		Body -> 1
		Tail -> 1
		Jaw -> 1
	Unbreakable:
		Head
		Arms
		Left Leg
		Right Leg

Azure Rathalos:
	Breakable:
		Removable Tail -> 1
		Head -> 2
		Body -> 1
		Left Wing -> 1
		Right Wing -> 1
	Unbreakable:
		Left Leg
		Right Leg
		Tail

Black Diablos:
	Breakable:
		Removable Horns -> 1, 2
		Removable Tail -> 1
		Body -> 1
	Unbreakable:
		Tail
		Head
		Left Wing
		Right Wing
		Left Leg
		Right Leg

Nergigante:
	Breakable:
		Removable Horns -> 2, 3
		Removable Tail -> 1
	Unbreakable:
		Horns
		Head
		Body
		Tail
		Left Arm
		Right Arm
		Left Leg
		Right Leg
		Left Wing
		Right Wing

Teostra:
	Breakable:
		Removable Tail -> 1
		Wings -> 1
		Head -> breakable when health < 15% and part's health is 0
	Unbreakable:
		Body
		Arms
		Legs
		Tail
		
Lunastra:
	Breakable:
		Removable Tail -> 1
		Lefy Wing -> 2
		Right Wing -> 2
		Head -> breakable when health < 15% and part's health is 0
	Unbreakable:
		Body
		Limbs
		Tail

Kushala Daora:
	Breakable:
		Removable Tail -> 1
		Head -> breakable when health < 15% and part's health is 0
		Wings -> 2
	Unbreakable:
		Body
		Tail
		Left Limbs
		Right Limbs

Vaal Hazak:
	Breakable:
		Tail -> 2 (cuts the tail)
		Head -> 2
		Chest -> 1
		Left Arm -> 1
		Right Arm -> 1
	Unbreakable:
		Back
		Left Leg
		Right Leg
		Wings
		Removable Tail -> doesn't work, changes even when not hiting the tail, maybe wrong memory address?

Xeno'jiiva:
	Breakable:
		Removable Tail -> 1
		Wings -> 2
		Head -> 2
		Left Arm -> 2
		Right Arm -> 2
	Unbreakable:
		The rest
```

**Comment by Haato3o** [comment]
Some monsters have unknown parts that no one really knows what they are (Vaal Hazak for example), so I just went with common sense and got the part name order from Smarthunter. Anyways, I was testing Vaal Hazak and apparently that *removable tail* isn't actually a tail. It's their whole body, but I don't know exactly why and what exactly happens when the health reaches 0 other than increasing the break counter.
I've also checked the [Library Of Babel](https://drive.google.com/file/d/1XPQ7FEYtGSl5MaX0d4Gd5gm8JmCYycjq/view) and Vaal Hazak's severable parts are listed as `Unk0` and `Unk1`.

**Comment by Haato3o** [comment]
I'm messing with the monster data now to find wrong parts, the Odogaron tail is also wrong. It's showing their whole body (same thing that is happening to Vaal Hazak) instead of tail, the removable tail is actually the second part in the removable parts list.

```xml
<!-- Wrong monster data for Odogaron -->
<Parts Max="6">
      <Part Name="MONSTER_PART_REMOVABLE_TAIL" IsRemovable="True"/>
      <Part Name="MONSTER_PART_HEAD" Group="HEAD" IsRemovable="False"/>
      <Part Name="MONSTER_PART_BODY" Group="BODY" IsRemovable="False"/>
      <Part Name="MONSTER_PART_ARMS" Group="ARM" IsRemovable="False"/>
      <Part Name="MONSTER_PART_LEGS" Group="LEG" IsRemovable="False"/>
      <Part Name="MONSTER_PART_TAIL" Group="TAIL" IsRemovable="False"/>
    </Parts>

<!-- Right monster data for Odogaron -->
<Parts Max="7">
      <Part Name="MONSTER_PART_REMOVABLE_HEAD" IsRemovable="True"/> <!-- This is unknown -->
      <Part Name="MONSTER_PART_REMOVABLE_TAIL" IsRemovable="True"/>
      <Part Name="MONSTER_PART_HEAD" Group="HEAD" IsRemovable="False"/>
      <Part Name="MONSTER_PART_BODY" Group="BODY" IsRemovable="False"/>
      <Part Name="MONSTER_PART_ARMS" Group="ARM" IsRemovable="False"/>
      <Part Name="MONSTER_PART_LEGS" Group="LEG" IsRemovable="False"/>
      <Part Name="MONSTER_PART_TAIL" Group="TAIL" IsRemovable="False"/>
    </Parts>
```

**Comment by Haato3o** [comment]
You can also enable a custom monster data to mess around if you want, I'll document it better soon, but for now to load a custom monster data:

- Open your `config.json`, scroll all the way down and change the value of `CustomMonsterData` from `null` to the path of your monster data file.
- Open HunterPie and in the Debug settings tab, enable the last option to load the custom monster data.
![option](https://cdn.discordapp.com/attachments/402557384209203200/695833223103643748/unknown.png)
- Restart HunterPie

> **Note:** You can find the monster data file [here](https://github.com/Haato3o/HunterPie/blob/master/HunterPie/Core/Monster/MonsterData.xml).

**Comment by nicodiaz55** [comment]
Thanks for all the info! I'll read and test those things that you mention tomorrow. Then I'll continue with Iceborne's monsters.

The good news are that at least for all these monsters from the base game, all of the "Part broken" notifications can be assigned to a bar, so we are not missing anything "important".

There could be more unknown parts that cause a flinch, as you said, but so far they don't show a notification, so this is good.

**Comment by nicodiaz55** [comment]
> I'm messing with the monster data now to find wrong parts, the Odogaron tail is also wrong. It's showing their whole body (same thing that is happening to Vaal Hazak) instead of tail, the removable tail is actually the second part in the removable parts list.
> 
> ```
> 
> <Parts Max="6">
>       <Part Name="MONSTER_PART_REMOVABLE_TAIL" IsRemovable="True"/>
>       <Part Name="MONSTER_PART_HEAD" Group="HEAD" IsRemovable="False"/>
>       <Part Name="MONSTER_PART_BODY" Group="BODY" IsRemovable="False"/>
>       <Part Name="MONSTER_PART_ARMS" Group="ARM" IsRemovable="False"/>
>       <Part Name="MONSTER_PART_LEGS" Group="LEG" IsRemovable="False"/>
>       <Part Name="MONSTER_PART_TAIL" Group="TAIL" IsRemovable="False"/>
>     </Parts>
> 
> 
> <Parts Max="7">
>       <Part Name="MONSTER_PART_REMOVABLE_HEAD" IsRemovable="True"/> 
>       <Part Name="MONSTER_PART_REMOVABLE_TAIL" IsRemovable="True"/>
>       <Part Name="MONSTER_PART_HEAD" Group="HEAD" IsRemovable="False"/>
>       <Part Name="MONSTER_PART_BODY" Group="BODY" IsRemovable="False"/>
>       <Part Name="MONSTER_PART_ARMS" Group="ARM" IsRemovable="False"/>
>       <Part Name="MONSTER_PART_LEGS" Group="LEG" IsRemovable="False"/>
>       <Part Name="MONSTER_PART_TAIL" Group="TAIL" IsRemovable="False"/>
>     </Parts>
> ```

Hello, I loaded this custom data and this fixes the Odogaron Removable Tail, when the count is 1, the tail is cut.

One thing I noticed is that "Removable Head" is actually a kind of trigger: every time its health is 0, Odogaron falls and proceeds to do his "counterattack combo". The same goes for Ebony Odogaron, but with the Removable Tail's bar (no custom data loaded).

I'm finishing testing the Iceborne's monsters and will report the results soon.

**Comment by nicodiaz55** [comment]
I found something interesting for Ruiner Nergigante. The actual data for it is wrong, so I changed the `MonsterData.xml` and added some "unknown removable parts" to it, like this:
```xml
    <Parts Max="23">
      <Part Name="MONSTER_PART_HORNS" Group="HORN" IsRemovable="False"/>
      <Part Name="MONSTER_PART_HEAD" Group="HEAD" IsRemovable="False"/>
      <Part Name="MONSTER_PART_BODY" Group="BODY" IsRemovable="False"/>
      <Part Name="MONSTER_PART_LARM" Group="ARM" IsRemovable="False"/>
      <Part Name="MONSTER_PART_RARM" Group="ARM" IsRemovable="False"/>
      <Part Name="MONSTER_PART_LLEG" Group="LEG" IsRemovable="False"/>
      <Part Name="MONSTER_PART_RLEG" Group="LEG" IsRemovable="False"/>
      <Part Name="MONSTER_PART_LWING" Group="WING" IsRemovable="False"/>
      <Part Name="MONSTER_PART_RWING" Group="WING" IsRemovable="False"/>
      <Part Name="MONSTER_PART_TAIL" Group="TAIL" IsRemovable="False"/>
      <Part Name="MONSTER_PART_UNKNOWN" IsRemovable="True"/>
      <Part Name="MONSTER_PART_UNKNOWN" IsRemovable="True"/>
      <Part Name="MONSTER_PART_UNKNOWN" IsRemovable="True"/>
      <Part Name="MONSTER_PART_UNKNOWN" IsRemovable="True"/>
      <Part Name="MONSTER_PART_UNKNOWN" IsRemovable="True"/>
      <Part Name="MONSTER_PART_UNKNOWN" IsRemovable="True"/>
      <Part Name="MONSTER_PART_UNKNOWN" IsRemovable="True"/>
      <Part Name="MONSTER_PART_UNKNOWN" IsRemovable="True"/>
      <Part Name="MONSTER_PART_UNKNOWN" IsRemovable="True"/>
      <Part Name="MONSTER_PART_UNKNOWN" IsRemovable="True"/>
      <Part Name="MONSTER_PART_UNKNOWN" IsRemovable="True"/>
      <Part Name="MONSTER_PART_UNKNOWN" IsRemovable="True"/>
      <Part Name="MONSTER_PART_UNKNOWN" IsRemovable="True"/>
    </Parts>
```
The first 10 parts are ok.

---
What I discovered is that some of these unknown parts change their total health value, and sometimes their position (list order). Sometimes they even disappear or display `0/NaN`.

But... I managed to gather some information after many tests (note: HP values are for solo):
- There's a bar for the `Removable Horns`, always with 1380 HP, breakable at 2 (first horn) and 4 (second horn).
- There's a bar for the `Removable Tail`, always with 2070 HP, breakable at 1.
- Theres' a bar for the silver spikes in its head, always with 1840 HP, breakable at 1.
- Theres' a bar for the silver spikes in its left arm, always with 1840 HP, breakable at 1.
- Theres' a bar for the silver spikes in its right arm, always with 2300 HP, breakable at 1.
- Theres' a bar for the silver spikes in its left wing, always with 920 HP, breakable at 1.
- Theres' a bar for the silver spikes in its right wing, always with 920 HP, breakable at 1.

After reaching 0, these parts are broken and their HP will never update again. So, somehow we could identificate those parts by its HP value...

---

Also there are bars for the white and black spikes:
- Head
- Tail
- Left Arm
- Right Arm
- Left Wing
- Right Wing

Each one of these bars change value depending if they are currently white or black, and they are persistant. For example (ignore the numbers), "Head" currently has white spikes, so it's health is 480/480. We damage it so now is has 200/480 HP. After some time, the spikes become black, so now this bar changes and has 800/800 HP. We continue dealing damage and the spikes have 650/800 HP. Then, the spikes become white again, so this bar changes again and now has 200/480 HP (same as before becoming black).

The spikes breaks when they reach 0 (and Nergigante flinches). But sometimes Nergigante itself removes them (changing the their HP value). This only happens with these part bars.

---

The problem is, as I said before, all these bars change position over time, and I don't know what triggers it.

You can see it if you change MonsterData.xml like this:

```xml
    <Parts Max="23">
      <Part Name="MONSTER_PART_HORNS" Group="HORN" IsRemovable="False"/>
      <Part Name="MONSTER_PART_HEAD" Group="HEAD" IsRemovable="False"/>
      <Part Name="MONSTER_PART_BODY" Group="BODY" IsRemovable="False"/>
      <Part Name="MONSTER_PART_LARM" Group="ARM" IsRemovable="False"/>
      <Part Name="MONSTER_PART_RARM" Group="ARM" IsRemovable="False"/>
      <Part Name="MONSTER_PART_LLEG" Group="LEG" IsRemovable="False"/>
      <Part Name="MONSTER_PART_RLEG" Group="LEG" IsRemovable="False"/>
      <Part Name="MONSTER_PART_LWING" Group="WING" IsRemovable="False"/>
      <Part Name="MONSTER_PART_RWING" Group="WING" IsRemovable="False"/>
      <Part Name="MONSTER_PART_TAIL" Group="TAIL" IsRemovable="False"/>
      <Part Name="MONSTER_PART_HEAD" IsRemovable="True"/> <!-- bw spikes -->
      <Part Name="MONSTER_PART_LARM" IsRemovable="True"/> <!-- bw spikes -->
      <Part Name="MONSTER_PART_LWING" IsRemovable="True"/> <!-- bw spikes -->
      <Part Name="MONSTER_PART_RWING" IsRemovable="True"/> <!-- bw spikes -->
      <Part Name="MONSTER_PART_RARM" IsRemovable="True"/> <!-- bw spikes -->
      <Part Name="MONSTER_PART_TAIL" IsRemovable="True"/> <!-- bw spikes -->
      <Part Name="MONSTER_PART_REMOVABLE_HORNS" IsRemovable="True"/> <!-- two horns  -->
      <Part Name="MONSTER_PART_REMOVABLE_TAIL"IsRemovable="True"/><!-- removable tail -->
      <Part Name="MONSTER_PART_HEAD" IsRemovable="True"/> <!-- silver spikes -->
      <Part Name="MONSTER_PART_LARM" IsRemovable="True"/> <!-- silver spikes -->
      <Part Name="MONSTER_PART_RARM" IsRemovable="True"/> <!-- silver spikes -->
      <Part Name="MONSTER_PART_LWING" IsRemovable="True"/> <!-- silver spikes -->
      <Part Name="MONSTER_PART_RWING" IsRemovable="True"/> <!-- silver spikes -->
    </Parts>
```

**Comment by nicodiaz55** [comment]
I finished to test every monster. Here's the list of each part that is breakable (displays in-game notification).

I didn't include:
-  Leshen and Ancient Leshen: they're difficult to test, and some bars are wrong
-  Shara Ishvalda: it has SO many parts (and almost all of then break at 1)
-  Ruiner Nergigante: see previous comment
-  Kulve Taroth: not available yet

```
Great Jagras:
		Head -> 2
		Arms -> 1
		Abdomen -> 3

Kulu-Ya-Ku:
		Head -> 1
		Arms -> 1

Pukei-Pukei:
		Removable Tail -> 1
		Head -> 2
		Left Wing -> 1
		Right Wing -> 1
		Body -> 1

Barroth:
		Breakable Head -> 1
		Muddy Head -> 1
		Muddy Body -> 1
		Arms -> 1
		Muddy Arms -> 1
		Left Leg -> 1
		Muddy Left Leg -> 1
		Right Leg -> 1
		Muddy Right Leg -> 1
		Muddy Tail -> 1
		Removable Tail -> 1

Jyuratodus:
		Head -> 4
		Muddy Head -> 1
		Body -> 1
		Muddy Body -> 3
		Muddy Tail -> 1 
		Tail -> 3
		Left Leg -> 2
		Right Leg -> 2
		Muddy Left Leg -> 2
		Muddy Right Leg -> 2
		
Tobi-Kadachi:
		Head -> 2
		Mane -> 1
		Arms -> 1
		Tail -> 4
		
Anjanath:
		Removable Tail -> 1
		Head -> 5
		Left Leg -> 3
		Right Leg -> 3
		
Rathian:
		Removable Tail -> 1
		Head -> 2
		Body -> 1
		Left Wing ->  1
		Right Wing ->  1

TziTzi-Ya-Ku:
		Head -> 2
		
Paolumu:
		Removable Balloon -> 1
		Left Wing -> 1
		Right Wing -> 1
		Body -> 1
		Tail -> 1

Great Girros:
		Head -> 2
		Removable Tail -> 1
		Arms -> 1
		
Radobaan:
		Removable Tail -> 1
		Jaw -> 1, 2
		Back -> 1, 2
		Left Bone -> 1, 2
		Right Bone -> 1, 2

Legiana:
		Head -> 2
		Body -> 1
		Left Wing -> 1
		Right Wing -> 1
		Tail -> 1

Odogaron:
		Tail -> 1
		Removable Tail -> 1
		Head -> 1, 2
		Arms -> 1
		Legs -> 1
		
Rathalos:
		Body -> 1
		Head -> 2
		Left Wing -> 1
		Right Wing -> 1
		Removable Tail -> 1
		
Diablos:
		Removable Horns -> 1, 2
		Removable Tail -> 1
		Body -> 1
		
Kirin:
		Head -> 8
		
Zorah Magdaros:
		Exhaust Organ Central -> 1
		Exhaust Organ Head -> 1

Dodogama:
		Removable Tail -> 1
		Head -> 5
		Arms -> 1

Pink Rathian:
		Removable Tail -> 1
		Head -> 2
		Body -> 1
		Left Wing -> 1
		Right Wing -> 1
		
Bazelgeuse:
		Removable Tail -> 1
		Head -> 2
		Left Wing -> 1
		Right Wing -> 1
		Body -> 1
		
Deviljho:
		Head -> 3
		Chest -> 5
		Removable Tail -> 1

Lavasioth:
		Head -> 6
		Body -> 2
		Tail -> 4
		Left Leg -> 4
		Right Leg -> 4

Uragaan:
		Removable Tail -> 1
		Body -> 1
		Tail -> 1
		Jaw -> 1

Azure Rathalos:
		Removable Tail -> 1
		Head -> 2
		Body -> 1
		Left Wing -> 1
		Right Wing -> 1

Black Diablos:
		Removable Horns -> 1, 2
		Removable Tail -> 1
		Body -> 1

Nergigante:
		Removable Horns -> 2, 3
		Removable Tail -> 1

Teostra:
		Removable Tail -> 1
		Wings -> 1
		Head -> after total health < 15%, the first time part break reaches 0 health
		
Lunastra:
		Removable Tail -> 1
		Lefy Wing -> 2
		Right Wing -> 2
		Head -> after total health < 15%, the first time part break reaches 0 health

Kushala Daora:
		Removable Tail -> 1
		Head ->  after total health < 15%, the first time part break reaches 0 health
		Wings -> 2	

Vaal Hazak:
		Removable Tail -> 1
		Head -> 2
		Chest -> 1
		Left Arm -> 1
		Right Arm -> 1		

Xeno'jiiva:
		Removable Tail -> 1
		Wings -> 2
		Head -> 2
		Left Arm -> 2
		Right Arm -> 2

Beotodus:
		Head -> 2
		Snowy Head -> 1
		Body -> 1
		Snowy Body -> 1
		Legs -> 2
		Tail -> 1 
		Snowy Tail -> 1

Banbaro:
		Removable Horns -> 1, 2
		Removable Tail -> 1
		Left Leg -> 1
		Right Leg -> 1

Viper Tobi-Kadachi:
		Head -> 2
		Mane -> 1
		Arms -> 1
		Tail -> 1

Nightshade Paolumu:
		Removable Balloon -> 1
		Left Wing -> 1
		Right Wing -> 1
		Body -> 1
		Tail -> 1

Coral Pukei-Pukei:
		Removable Tail -> 1
		Head -> 2
		Left Wing -> 1
		Right Wing -> 1
		Body -> 1

Barioth:
		Removable Tail -> 1
		Head -> 4
		Left Arm -> 1
		Right Arm -> 1

Nargacuga:
		Removable Tail -> 1
		Head -> 4
		Left Arm -> 1
		Right Arm -> 1

Glavenus:
		Head -> 1, 2
		Removable Tail -> 1
		Fin -> 1
		Arms -> 1
		Tail -> 1

Tigrex:
		Removable Tail -> 1
		Head -> 1
		Left Arm -> 2
		Right Arm -> 2

Brachydios:
		Head -> 4
		Left Arm -> 2
		Right Arm -> 2
		Removable Tail -> 1

Raging Brachydios:
		Head -> 2
		Left Arm -> 2
		Right Arm -> 2
		Removable Tail -> 1

Shrieking Legiana:
		Head -> 2
		Left Wing -> 1
		Right Wing -> 1
		Tail -> 1
		Body -> 1	

Fulgur Anjanath:
		Removable Tail -> 1
		Head -> 5
		Left Leg -> 3
		Right Leg -> 3

Acidic Glavenus:
		Removable Tail -> 1
		Fin -> 1
		Head -> 1, 2
		Tail -> 1
		Arms -> 1

Ebony Odogaron:
		Breakable Head -> 1
		Removable Tail -> 1
		Arms -> 1
		Legs -> 1
		Tail > 1

Velkhana:
		Removable Tail -> 1
		Head -> 2
		Wings -> 2

Seething Bazelgeuse:
		Removable Tail -> 1
		Head -> 2
		Body -> 1
		Left Wing -> 1
		Right Wing -> 1

Blackveil Vaal Hazak:
		Head -> 3
		Chest -> 1
		Left Arm -> 1
		Right Arm -> 1
		Removable Tail -> 1

Namielle:
		Removable Tail -> 1
		Head -> 5
		Wings -> 2
		Arms -> 2

Savage Deviljho:
		Head -> 2
		Chest -> 2
		Removable Tail -> 1

Ruiner Nergigante: (HP in Guiding Lands, 1 player)
		Removable Horn -> 2, 4 (1380 HP)
		Removable Tail -> 1 (2070 HP)
		Head Silver Spikes -> 1 (1840 HP)
		Left Arm Silver Spikes -> 1 (1840 HP)
		Right Arm Silver Spikes -> 1 (2300 HP)
		Left Wing Silver Spikes -> 1 (920 HP)
		Right Wing Silver Spikes -> 1 (920 HP)

Zinogre:
		Head -> 2, 4
		Arms -> 2
		Removable Tail -> 1
		Back -> 1

Yian Garuga:
		Removable Tail -> 1
		Head -> 2, 4
		Body -> 1
		Left Wing -> 1
		Right Wing -> 1

Scarred Yian Garuga:
		Removable Tail -> 1
		Head -> 2, 4
		Body -> 1
		Left Wing -> 1
		Right Wing -> 1

Brute Tigrex:
		Removable Tail -> 1
		Head -> 1
		Left Arm -> 2
		Right Arm -> 2

Gold Rathian:
		Removable Tail -> 1
		Head -> 2
		Body -> 1
		Left Wing -> 1
		Right Wing -> 1

Silver Rathalos:
		Removable Tail -> 1
		Head -> 2
		Body -> 1
		Left Wing -> 1
		Right Wing -> 1

Rajang:
		Removable Horn -> 1
		Removable Horn 2 -> 1
		Left Arm -> 1
		Right Arm -> 1
		Removable Tail -> 1

Furious Rajang:
		Removable Horn -> 1
		Removable Horn 2 -> 1
		Left Arm -> 1
		Right Arm -> 1

Stygian Zinogre:
		Head -> 2, 4
		Arms -> 3
		Removable Tail -> 1
		Back -> 1

Safi'jiiva:
		Removable Tail -> 1
		Head -> 5, 10
		Abdomen -> 1
		Back -> 1
		Left Arm -> 7
		Right Arm -> 7
		Left Leg -> 5
		Right Leg -> 5
		Left Wing -> 3
		Right Wing -> 3

Behemoth:
		Removable Tail -> 1
		Horns -> 2, 3
		Left Arm -> 3
		Right Arm -> 3
```

**Comment by Haato3o** [comment]
Thanks! I'll add them to the monster data so I can implement them in the monster part bars

**Comment by nicodiaz55** [comment]
Awesome, thanks a lot!

**Comment by nicodiaz55** [comment]
Breakable parts for Kulve Taroth:

```
Kulve Taroth:
		Removable Horns -> 1
		Removable Horns #2 -> 1
		Golden Horns -> 1
		Golden Left Chest -> 1
		Golden Right Chest -> 1
		Golden Left Arm -> 1
		Golden Right Arm -> 1
		Golden Left Leg -> 1
		Golden Right Leg -> 1
		Golden Left Tail -> 1
		Golden Right Tail -> 1
		Tail -> 1
		Horns -> 1
```

**Comment by Haato3o** [comment]
@nicodiaz55 I pushed HunterPie v1.0.3.90 today to BETA branch, you can test the broken counter if you want :)
Settings > General > Select "BETA" in the Update branch options.

**Comment by nicodiaz55** [comment]
Sorry for the late response, it works perfectly! Thanks a lot, now it's easier to focus on breaking monster parts :) 

Can I make another suggestion? 
- Have an option to show only the breakable parts and hide the "flinch only" parts (i.e. show only parts with broken counter)

Thanks!

**Comment by Haato3o** [comment]
> Have an option to show only the breakable parts and hide the "flinch only" parts (i.e. show only parts with broken counter)
Oh, sure. I can add an option for that

**Comment by nicodiaz55** [comment]
Woah, I guess in the last update they changed some monster parts...

I just hunted a Banbaro and what it was its `Removable Tail` now it's another `Removable Horn`. Even worse: they both decrease at the same time, wich is ridiculous because both break at 1 and 2 at the same time. The "real" `Removable Tail` is nowhere to be found (maybe we have to add another `IsRemovable="True"`...).

I'm gonna test all the monsters again and will submit a pull request when I gather all this new information.

**Comment by nicodiaz55** [comment]
I'm closing this issue since well, it's implemented.
