### ISSUE TITLE
Affinity booster - buff bar

### ISSUE THREAD

**Issue by luzclasil** [Haato3o/HunterPie#34]
Not sure if it has been implemented already and I was just unable to find it but it would be very helpful if I could know for how much time my affinity booster is/will be active so I don't have to walk across it every 5 sec. I already know that through the "specialized tools" options it enables me to know how much time the booster will be active. Then, once it expires I know it shows the remaining recharge time but I haven't been able to find for how long the buff per se will be active on me once I walk across it... Thanks!

**Comment by Haato3o** [comment]
The abnormalities tray widget is still missing some buffs, they will be added whenever I find them in memory, might take some time until I find them all, but eventually HunterPie will support all buffs (or at least most of them).

**Comment by luzclasil** [comment]
> The abnormalities tray widget is still missing some buffs, they will be added whenever I find them in memory, might take some time until I find them all, but eventually HunterPie will support all buffs (or at least most of them).

Ohh, thank you for pointing it out. It's good to know I was not just overlooking something...
Hopefully it won't take that long for you to find it out so good luck and thanks again!
Feel free to close this thread now :)

**Comment by Haato3o** [comment]
I'll keep this open until I find the affinity booster buff, so I can let you know

**Comment by F-a-y-t-h** [comment]
Buff offsets you seem to be missing (also most buffs seems to be -4 on this update) 7D20 ->
6CC : Demon Ammo
6D0 : Armour Ammo
76C : Protective Polish
770 : Affinity Slider 

Affinity booster Buff Duration is using another offset 12608 -> FC8

**Comment by Haato3o** [comment]
> 
> 
> Buff offsets you seem to be missing (also most buffs seems to be -4 on this update) 7D20 ->
> 6CC : Demon Ammo
> 6D0 : Armour Ammo
> 76C : Protective Polish
> 770 : Affinity Slider
> 
> Affinity booster Buff Duration is using another offset 12608 -> FC8

Yea, I noticed that when I was mapping the addresses for today's update. Apparently all consumable and armor buffs got moved by 4 bytes. I only fixed the consumables for now since HunterPie doesn't support the armor/booster buffs yet, but I'll add them when I start implementing the rest of the buffs

**Comment by luzclasil** [comment]
Just reporting FYI...
You might already know that by now but just in case you don't... at least for me all the "buff bar" thingies are gone.
Either being buff (e.g. might seed) or debuff (e.g. poison) nothing seems to be working on the newest version (1.0.3.86). I've even tried re-configuring everything from scratch (new config.json file) but still no luck.

**Comment by Haato3o** [comment]
Capcom broke the buffs in this last update. I'm still fixing them

**Comment by Haato3o** [comment]
I added armor and specialized tool buffs to the supported buffs in v1.0.3.88
