### ISSUE TITLE
UI Scaling Controls

### ISSUE THREAD

**Issue by MushroomDynamo** [Haato3o/HunterPie#36]
I'm very much in love with how HunterPie's widgets look aesthetically, but as far as I can tell there's no configurability for the UI scale of individual widgets or their subelements--this can make some things a little hard to read at 3840x2160. Is it feasible to add controls for this?

**Comment by Haato3o** [comment]
You can rescale the widgets by pressing ScrollLock (or whatever HotKey you set for Design Mode), hovering your mouse over the widget and then scrolling up to scale the widget up and scroll down to scale the widget down, then press your design mode HotKey again to save the changes.

**Comment by MushroomDynamo** [comment]
My apologies, I somehow missed that when reading through the documentation--works great. Closing issue.
