### ISSUE TITLE
[Suggestion] export decoration and charm data to HoneyHunter-compatible strings

### ISSUE THREAD

**Issue by UncleClapton** [Haato3o/HunterPie#52]
HoneyHunter's set builder lets you set your decoration inventory using a comma separated list of quantities. There is also another list of charm levels for each charm. Do you think it would be possible to add a function that reads your player's decorations and charms to create these settings strings?

![honey hunter website](https://clapton.dev/u/2005/025368d6.png)

**Comment by Haato3o** [comment]
Sure, I'll talk to Honey about it

**Comment by DaviesCooper** [comment]
Hey, I'm not sure how else to get in contact with you. I've recently contributed to the AutoSteamWorks repo, and I'm wanting to start working on another project. This feature request seems easy enough that I feel like I would be able to develop it as a starting contribution. If you want to talk more about it please contact me at ctdavies@ucalgary.ca.

**Comment by Haato3o** [comment]
> Hey, I'm not sure how else to get in contact with you. I've recently contributed to the AutoSteamWorks repo, and I'm wanting to start working on another project. This feature request seems easy enough that I feel like I would be able to develop it as a starting contribution. If you want to talk more about it please contact me at [ctdavies@ucalgary.ca](mailto:ctdavies@ucalgary.ca).

@DaviesCooper, you can contact me on Discord, either by joining [HunterPie server](https://discord.gg/5pdDq4Q) or even in direct messages (Haato#0704). Feel free to work on the decoration and charm exporter, you can make the logic for it and I can add the export button to the UI. Just make sure to submit the PR to the development branch, not the master one.

**Comment by Haato3o** [comment]
Added in v1.0.3.93
