### ISSUE TITLE
Monster Overlay Toggle

### ISSUE THREAD

**Issue by Dave247** [Haato3o/HunterPie#6]
I noticed what i think is a bug with the monster overlay toggle, where it doesn't seem to do anything. Enabled the in game overlay acts as a global enable/disable as it should, however toggling the individual overlay for the monster health won;t work.

**Comment by Haato3o** [comment]
That bug is fixed now, I'll push a patch along with other enhancements and core code reworks I've worked on this past week. (https://github.com/Haato3o/HunterPie/commit/14eb245f8863c3186bffbf18daa979fdfe23c8d3)
