### ISSUE TITLE
Hide overlay while quest reward screen

### ISSUE THREAD

**Issue by Murkchan** [Haato3o/HunterPie#74]
Overlay messes to screenshot, need to hide overlay while quest reward screen (best if hidden when you press button to hide ingame HUD). 
Also same function for other screenshoting modes.

**Comment by Haato3o** [comment]
There's an overlay toggle hotkey though (Default: Ctrl+Alt+Z). Too much work to find that in memory, implement everything, map it every patch, when you can just press a hotkey.
