### ISSUE TITLE
Question about linux wine

### ISSUE THREAD

**Issue by kriptolix** [Haato3o/HunterPie#76]
I know this isn't the focus here, but I'm trying to run this mod on linux using wine. I'm know too that probably this won't work because of memory sandbox on wine, but I'm really curious because even after install .net framework 4.7.1 the application still report that can't find net framework libraries. Some clue of the reason?.

There is no overlay available for linux wine/proton players and this is kind of sad. Maybe if I can do the visual layer works I can fork this project to try do the memory read correctly on the wine.

**Comment by Haato3o** [comment]
Uh, I have no experience on developing for Linux and never used it, therefore never used Wine either, so I don't really know why it doesn't recognize your .NET framework after you've installed it.
