### ISSUE TITLE
Heroics/Potential gauge

### ISSUE THREAD

**Issue by Sinewyk** [Haato3o/HunterPie#79]
Hey, Heroics is kind of a pain in the ass to optimize for.

Any chance we could track current 35% of life so that when healing we can heal up to the limit to keep all advantages ?

A flat & percentage overlay tracker that we can put just on top of the health would be perfect I recon.

I'm leaving this here as a tracking issue ~but I may do it myself.~

edit: nevermind doing it myself, thought this was another project with a language I was practiced in.

**Comment by Haato3o** [comment]
Sorry, I've been busy with the Monster core rewrite lately, but I can add that to the [suggestions list](https://trello.com/b/oDDhrqZb/hunterpie-development).

**Comment by Sinewyk** [comment]
Sure, no problem.

Excellent software btw 👍 

Closing this suggestion as it's not an issue.
