### ISSUE TITLE
Bug Report: Gunlance Wyvernsfire Cooldown

### ISSUE THREAD

**Issue by CmdrVoid** [Haato3o/HunterPie#84]
When using gunlance the Wyvernsfire´s outline around the stake timer doesnt go red anymore.

**Comment by Haato3o** [comment]
Oh, latest update moved some buffs offsets. I'll fix it.

**Comment by Haato3o** [comment]
Fixed in https://github.com/Haato3o/HunterPie/commit/36ee9548c0c68d310bcb74bfd405f9caea5052c1
