### ISSUE TITLE
Element cap Alatreon

### ISSUE THREAD

**Issue by lucaskiu** [Haato3o/HunterPie#87]
Hello, is there any possibility to add the Alatreon element cap? So we would know it necessary to diminish his power for the SuperNova. If it is possible. Appreciate. Thanks for Nice work with overlay.

**Comment by Haato3o** [comment]
Done! I just pushed the update, just restart your HunterPie so it can auto update! 
(Commit: https://github.com/Haato3o/HunterPie/commit/550cec93433a752dec7a1da543ecfcddb17f13ab)
