### ISSUE TITLE
游戏一更新，ｈｕｎｔｅｒｐｉｅ就直接失效了

### ISSUE THREAD

**Issue by resplendent-star** [Haato3o/HunterPie#89]

**Comment by Haato3o** [comment]
Uh, I don't speak chinese. Can you describe your problem in english instead so I can help you out?

**Comment by resplendent-star** [comment]
> 嗯，我不会说中文。您可以用英语来描述您的问题，以便我为您提供帮助吗？

sorry,i dont know, the problem  is  once the MHW  updated by provider,the hunterpie cant work anymore,for example, MHW updated  yesterday,hunterpie cant work

**Comment by Haato3o** [comment]
Your firewall is probably blocking HunterPie from updating itself. Make an exception for both `HunterPie.exe` and `Update.exe` in your Firewall rule settings and run HunterPie so it can get the latest files.

**Comment by resplendent-star** [comment]
> Your firewall is probably blocking HunterPie from updating itself. Make an exception for both `HunterPie.exe` and `Update.exe` in your Firewall rule settings and run HunterPie so it can get the latest files.

fine
