### ISSUE TITLE
Images for stages

### ISSUE THREAD

**Issue by Haato3o** [Haato3o/HunterPie#9]
There are some stages missing images.
- [x] Great Ravine (st106, st107)
- [x] The Guiding Lands (st109)
- [x] Introduction (st401)
- [x] Everstream (st403)
- [x] Confluence of Fates (st405)
- [x] Ancient Forest (intro) (st406)
- [x] Caverns of El Dorado (st409)
- [x] Chamber of Five (st505)

**Comment by Dave247** [comment]
I assume you mean for the `largeImageKey` (ie the bigger square image)? I've been playing the game a fair bit lately so I can take a few screenshots for you of those locations.
Is there anything in particular that you are looking for in them? Or does it not really matter too much seeing as you'd just be cropping a small section out of the full desktop screenshot.

**Comment by Haato3o** [comment]
Hi, it doesn't really matter, I just try to keep the screenshots in a good angle so people can tell which region the player is in just by looking at the bigger square image. Feel free to send images, there's a list of missing stages in this issue but you can send other stages too if you want. Just send the image and name it stNNN.png (NNN would be the stage ID that you can get by looking at your console log).

**Comment by Dave247** [comment]
Fair enough, I'll just focus on the one's that are missing as I haven't actually I looked at all the current images for the different areas as I'm the only one I know that's currently using the program.
 
Getting the Chamber of Five and Great Ravne one's are going to be tricky as the first you had to have gone there before gone too far in the story (maybe you can just create a new character?) and the other is only used for two quests for the story as far as I am aware.
For those two it might be worth looking on one of the Monster Hunter wiki's or maybe even taking a screenshot from someone's Youtube video if it comes to that.

**Comment by Dave247** [comment]
> ZoneID 401 is at the very start when you get control of your character following the first few cutscenes, where you get knocked off the ship and all onto Zora's back. I've included what is hopefully a good screenshot
![MonsterHunterWorld_2020-01-29_18-51-05](https://user-images.githubusercontent.com/10183015/73340558-0fdc9800-42cf-11ea-8d3b-e20b867f63e9.jpg)

**Comment by Dave247** [comment]
Here's a screenshot of 505
![MonsterHunterWorld_2020-01-29_19-43-39](https://user-images.githubusercontent.com/10183015/73341019-e5d7a580-42cf-11ea-9b84-66434ab8a170.jpg)

**Comment by TheFuzzy** [comment]
The Guiding Lands (st109)

I did not have my graphics settings maxed though (other than HD textures), hope it's good enough.

![20200203213746_1](https://user-images.githubusercontent.com/4396695/73657767-ee641d80-46cd-11ea-8fd1-b91f9a80d107.jpg)

**Comment by Haato3o** [comment]
Thanks, I'll add it to the rich presence assets.

**Comment by Dave247** [comment]
Here's one of the Everstream I took a few days ago but forgot to upload
![MonsterHunterWorld_2020-01-29_23-52-35](https://user-images.githubusercontent.com/10183015/73710526-5fe8ae00-4758-11ea-8b94-e5ca1e1515df.jpg)
 until now.
