### ISSUE TITLE
Overlay

### ISSUE THREAD

**Issue by Snickerdog** [Haato3o/HunterPie#93]
I don't know why but when i started using hunterpie it worked fine, but after a little while of using it like 2 weeks the overlay would not appear anymore ingame. If i Alt+Tab it shows the overlay, but once i clip back in the game its gone. I've tried redownloading it and it still doesn't show it and i'm not sure whats wrong. Maybe it's something simple to fix but I couldn't find anything online about how to fix it. Enable overlay is on.

**Comment by Haato3o** [comment]
From FAQ:
![image](https://user-images.githubusercontent.com/35552782/89234987-ae6dec80-d5c3-11ea-8a83-a4fb42b2632f.png)

Also, if you've updated your graphics card driver recently, that might be the issue, rolling back to an older version should fix that.

**Comment by Snickerdog** [comment]
Thank you
