### ISSUE TITLE
Noticable stuttering while using HunterPi

### ISSUE THREAD

**Issue by FluffyDiscord** [Haato3o/HunterPie#94]
Hello, I am experiencing terrible stuttering while fighting any boss using this program. I am running steam version on r7 2700 @4Ghz. HW acceleration makes it even worse. No matter the branch, if main or beta.

full system

r7 2700
rx 5700 xt
4x8gb ram
windows 10

**Comment by GIitchy** [comment]
Do you use any variable sync technology (freesync, g-sync)? There is an issue with the framework that HunterPie use that lead to fps loss/stuttering.

**Comment by FluffyDiscord** [comment]
I do use freesync

**Comment by GIitchy** [comment]
Turn it off for MHWI and your issue should be fixed.
