### ISSUE TITLE
Safi chest partbreak issue

### ISSUE THREAD

**Issue by MintyFreshGum** [Haato3o/HunterPie#98]
Not sure if I am missing something or if this is not actually a bug, but Safi's chest does not appear to show as a breakable part in the overlay. There is a part labeled "Abdomen" which appears breakable, but did not break when the chest actually broke. Just wanted to check if this was known or not, or if it was purposeful behavior.

**Comment by Haato3o** [comment]
The `Abdomen` is the same as her chest, however, you only actually damage her chest when she is in critical state (which is something HunterPie can't track at the moment). When she is not in critical state, you're damaging her abdomen, but they share the same "part" in memory.
This is not a bug, but it's not really accurate either, I just haven't had time to look into it yet and implement a proper fix for it.

**Comment by Haato3o** [comment]
Actually, apparently her Chest was actually labeled as "Neck". I updated the monster data to fix the misslabel (https://github.com/Haato3o/HunterPie/commit/895b55078b7c653e08663b7f1b2ec3aea8d6d3f8)
